"""Remove foreign key from Expense

Revision ID: 582c7b4f3d07
Revises: 09d48d691e34
Create Date: 2024-11-09 23:17:29.676409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c7b4f3d07'
down_revision = '09d48d691e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('expenses_budget_id_fkey', type_='foreignkey')
        batch_op.drop_column('budget_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expenses_budget_id_fkey', 'budgets', ['budget_id'], ['id'])

    # ### end Alembic commands ###
